### ISSUE TITLE
Pitch deck for Submission

### ISSUE THREAD

**Issue by MaxKuck** [deora-earth/kiezDAO#11]
# Bounty
Create a pitch deck to present our purpose, the app + features and the big picture of future communities. 

## Scope
- gdrive presentation 
- 1min intro to deora and purpose and how KiezDAO is alligned with it
- integration of smart contract functionality and cello integration
- concentrate on the core features of the app - more like a sells pitch on the impact of the app, rather than the single features as covered in issue #10 

## Deliverables
- gdrive presentation as pitch

## Gain for the project
Requirement for the submission 

## Roles
bounty gardener: @MaxKuck  / 10%  
bounty worker: @MaxKuck  / 80%  
bounty reviewer: @DistributedDoge  / 10%

**Comment by DistributedDoge** [comment]
Sharing a note from organizers on what should be inside a Deck. 

Prepare a pitch deck and video presentation that includes the following:
- Vision and value proposition
- Problem the team is solving
- Target market and opportunity
- The solution
- Revenue model or business model/Impact measurement 
- Competitive Analysis 
- Plan to Validate Customer Segments
- Plan to Define and Validate MVP
- KPIs for Success
Team Bio

**Comment by MaxKuck** [comment]
presentation here: https://docs.google.com/presentation/d/1Aat-ShsEHyUCICKHfo60si6jlt45P7oKgIBy_suXN6w/edit?usp=sharing

**Comment by DistributedDoge** [comment]
Really professional looking slides, great job, closing.
