### ISSUE TITLE
Survey with pilot users

### ISSUE THREAD

**Issue by MaxKuck** [deora-earth/kiezDAO#12]
# Bounty
Target group survey

## Scope
- create a survey with 5-8 questions
- interview people we know
- make 3-4 interviews 

## Deliverables
- pdf with different answers to each question

## Gain for the project
insights about our pilot users

## Roles
bounty gardener: @MaxKuck / 10%  
bounty worker: @zschavi / 80%  
bounty reviewer: @DistributedDoge   / 10%

**Comment by zschavi** [comment]
:boat:KiezDAO Survey - ready for review :boat:
I tried to squeeze as much as possible from Jacob's brilliant email:
https://hackmd.io/2Ki56daIT2CY9LDsWG2UYg?view

**Comment by zschavi** [comment]
took longer than expected, please resize to 350 if possible 

🙏

**Comment by DistributedDoge** [comment]
Nicely done, approved and put the survey in the repository. Closing.
