### ISSUE TITLE
Create reputation_system.md and community_fund.md

### ISSUE THREAD

**Issue by MaxKuck** [deora-earth/kiezDAO#8]
# Bounty
Describe the content and functionality of a reputation system and of the community fund.

## Scope
- set up md file and images for better explanation
- link to files if each of them is mentioned in the other documents

## Deliverables
two .md files explaining each concept 

## Gain for the project
Better understanding of our USP and our ideas of digital tribe/community.

## Roles
bounty gardener: @MaxKuck  / 10%  
bounty worker: @MaxKuck / 80% 
bounty reviewer: @DistributedDoge  / 10%

**Comment by DistributedDoge** [comment]
Good work, approved.  Closing the issue.
